In [1]:
import pandas as pd
from sqlalchemy import create_engine

In [2]:
article_file = "Resources/ArticlesApril2018.csv"

articles_df = pd.read_csv(article_file)
articles_df.head()

,articleID,articleWordCount,byline,documentType,headline,keywords,multimedia,newDesk,printPage,pubDate,sectionName,snippet,source,typeOfMaterial,webURL
0,5adf6684068401528a2aa69b,781,By JOHN BRANCH,article,Former N.F.L. Cheerleaders’ Settlement Offer: ...,"['Workplace Hazards and Violations', 'Football...",68,Sports,0,2018-04-24 17:16:49,Pro Football,"“I understand that they could meet with us, pa...",The New York Times,News,https://www.nytimes.com/2018/04/24/sports/foot...
1,5adf653f068401528a2aa697,656,By LISA FRIEDMAN,article,E.P.A. to Unveil a New Rule. Its Effect: Less ...,"['Environmental Protection Agency', 'Pruitt, S...",68,Climate,0,2018-04-24 17:11:21,Unknown,The agency plans to publish a new regulation T...,The New York Times,News,https://www.nytimes.com/2018/04/24/climate/epa...
2,5adf4626068401528a2aa628,2427,By PETE WELLS,article,"The New Noma, Explained","['Restaurants', 'Noma (Copenhagen, Restaurant)...",66,Dining,0,2018-04-24 14:58:44,Unknown,What’s it like to eat at the second incarnatio...,The New York Times,News,https://www.nytimes.com/2018/04/24/dining/noma...
3,5adf40d2068401528a2aa619,626,By JULIE HIRSCHFELD DAVIS and PETER BAKER,article,Unknown,"['Macron, Emmanuel (1977- )', 'Trump, Donald J...",68,Washington,0,2018-04-24 14:35:57,Europe,President Trump welcomed President Emmanuel Ma...,The New York Times,News,https://www.nytimes.com/2018/04/24/world/europ...
4,5adf3d64068401528a2aa60f,815,By IAN AUSTEN and DAN BILEFSKY,article,Unknown,"['Toronto, Ontario, Attack (April, 2018)', 'Mu...",68,Foreign,0,2018-04-24 14:21:21,Canada,"Alek Minassian, 25, a resident of Toronto’s Ri...",The New York Times,News,https://www.nytimes.com/2018/04/24/world/canad...

In [3]:
comment_file = "Resources/CommentsApril2018.csv"

comment_df = pd.read_csv(comment_file)
comment_df.head()

C:\Users\willi\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3020: DtypeWarning: Columns (32) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,approveDate,articleID,articleWordCount,commentBody,commentID,commentSequence,commentTitle,commentType,createDate,depth,...,status,timespeople,trusted,typeOfMaterial,updateDate,userDisplayName,userID,userLocation,userTitle,userURL
0,1524594282,5adf6684068401528a2aa69b,781.0,How could the league possibly refuse this offe...,26853969.0,26853969.0,<br/>,comment,1524594011,1.0,...,approved,1,0,News,1524594282,Christopher Rillo,46566740.0,San Francisco,NaN,NaN
1,1524594252,5adf6684068401528a2aa69b,781.0,"So then the execs can be like ""yeah...we will ...",26853699.0,26853699.0,<br/>,comment,1524593146,1.0,...,approved,1,0,News,1524594252,Matt Brand,64324866.0,"Williamsburg, Brooklyn",NaN,NaN
2,1524594250,5adf6684068401528a2aa69b,781.0,I would not want to play chess against these c...,26853677.0,26853677.0,<br/>,comment,1524593032,1.0,...,approved,1,0,News,1524594250,Joseph,78105093.0,"Fayetteville, AR",NaN,NaN
3,1524593431,5adf6684068401528a2aa69b,781.0,Could the cheerleaders join the Actors' Equity...,26853784.0,26853784.0,<br/>,comment,1524593426,1.0,...,approved,0,0,News,1524593431,Stephen,81939618.0,"Phoenix, AZ",NaN,NaN
4,1524595048,5adf653f068401528a2aa697,656.0,Seeking conclusions which support preconceived...,26854236.0,26854236.0,<br/>,comment,1524595043,1.0,...,approved,1,0,News,1524595048,Paul Zorsky,58642997.0,Texas,NaN,NaN

In [4]:
new_comments_data_df = comment_df[['articleID', 'commentBody', 'commentType','status', 'trusted', 'userDisplayName', 'userLocation']].copy()
new_comments_data_df.head()

,articleID,commentBody,commentType,status,trusted,userDisplayName,userLocation
0,5adf6684068401528a2aa69b,How could the league possibly refuse this offe...,comment,approved,0,Christopher Rillo,San Francisco
1,5adf6684068401528a2aa69b,"So then the execs can be like ""yeah...we will ...",comment,approved,0,Matt Brand,"Williamsburg, Brooklyn"
2,5adf6684068401528a2aa69b,I would not want to play chess against these c...,comment,approved,0,Joseph,"Fayetteville, AR"
3,5adf6684068401528a2aa69b,Could the cheerleaders join the Actors' Equity...,comment,approved,0,Stephen,"Phoenix, AZ"
4,5adf653f068401528a2aa697,Seeking conclusions which support preconceived...,comment,approved,0,Paul Zorsky,Texas

In [5]:
new_article_data_df = articles_df[['articleID', 'byline', 'articleWordCount','headline', 'keywords', 'typeOfMaterial']].copy()
new_article_data_df.head()

,articleID,byline,articleWordCount,headline,keywords,typeOfMaterial
0,5adf6684068401528a2aa69b,By JOHN BRANCH,781,Former N.F.L. Cheerleaders’ Settlement Offer: ...,"['Workplace Hazards and Violations', 'Football...",News
1,5adf653f068401528a2aa697,By LISA FRIEDMAN,656,E.P.A. to Unveil a New Rule. Its Effect: Less ...,"['Environmental Protection Agency', 'Pruitt, S...",News
2,5adf4626068401528a2aa628,By PETE WELLS,2427,"The New Noma, Explained","['Restaurants', 'Noma (Copenhagen, Restaurant)...",News
3,5adf40d2068401528a2aa619,By JULIE HIRSCHFELD DAVIS and PETER BAKER,626,Unknown,"['Macron, Emmanuel (1977- )', 'Trump, Donald J...",News
4,5adf3d64068401528a2aa60f,By IAN AUSTEN and DAN BILEFSKY,815,Unknown,"['Toronto, Ontario, Attack (April, 2018)', 'Mu...",News

In [6]:
merge_table = pd.merge(new_comments_data_df, new_article_data_df, on="articleID")
merge_table

,articleID,commentBody,commentType,status,trusted,userDisplayName,userLocation,byline,articleWordCount,headline,keywords,typeOfMaterial
0,5adf6684068401528a2aa69b,How could the league possibly refuse this offe...,comment,approved,0,Christopher Rillo,San Francisco,By JOHN BRANCH,781,Former N.F.L. Cheerleaders’ Settlement Offer: ...,"['Workplace Hazards and Violations', 'Football...",News
1,5adf6684068401528a2aa69b,"So then the execs can be like ""yeah...we will ...",comment,approved,0,Matt Brand,"Williamsburg, Brooklyn",By JOHN BRANCH,781,Former N.F.L. Cheerleaders’ Settlement Offer: ...,"['Workplace Hazards and Violations', 'Football...",News
2,5adf6684068401528a2aa69b,I would not want to play chess against these c...,comment,approved,0,Joseph,"Fayetteville, AR",By JOHN BRANCH,781,Former N.F.L. Cheerleaders’ Settlement Offer: ...,"['Workplace Hazards and Violations', 'Football...",News
3,5adf6684068401528a2aa69b,Could the cheerleaders join the Actors' Equity...,comment,approved,0,Stephen,"Phoenix, AZ",By JOHN BRANCH,781,Former N.F.L. Cheerleaders’ Settlement Offer: ...,"['Workplace Hazards and Violations', 'Football...",News
4,5adf6684068401528a2aa69b,We all know that if the cheerleaders were all ...,comment,approved,0,Greg,Seattle,By JOHN BRANCH,781,Former N.F.L. Cheerleaders’ Settlement Offer: ...,"['Workplace Hazards and Violations', 'Football...",News
5,5adf6684068401528a2aa69b,"Why even have cheerleaders, they are not part ...",comment,approved,0,The Iconoclast,Oregon,By JOHN BRANCH,781,Former N.F.L. Cheerleaders’ Settlement Offer: ...,"['Workplace Hazards and Violations', 'Football...",News
6,5adf6684068401528a2aa69b,"Nice photo of the legs by the way, is that the...",comment,approved,0,NYer,New York,By JOHN BRANCH,781,Former N.F.L. Cheerleaders’ Settlement Offer: ...,"['Workplace Hazards and Violations', 'Football...",News
7,5adf6684068401528a2aa69b,"""Dozens of current and former cheerleaders hav...",comment,approved,0,Jill Green,"Reidsville, NC",By JOHN BRANCH,781,Former N.F.L. Cheerleaders’ Settlement Offer: ...,"['Workplace Hazards and Violations', 'Football...",News
8,5adf6684068401528a2aa69b,"Roger Goodell makes $40,000,000 per year. At a...",comment,approved,0,veteran,jersey shore jersey,By JOHN BRANCH,781,Former N.F.L. Cheerleaders’ Settlement Offer: ...,"['Workplace Hazards and Violations', 'Football...",News
9,5adf6684068401528a2aa69b,I have only two wishes of my beloved NY Giants...,comment,approved,0,Frank,South Orange,By JOHN BRANCH,781,Former N.F.L. Cheerleaders’ Settlement Offer: ...,"['Workplace Hazards and Violations', 'Football...",News
10,5adf6684068401528a2aa69b,Wait. The cheerleaders are not insisting on d...,comment,approved,0,John,NH NH,By JOHN BRANCH,781,Former N.F.L. Cheerleaders’ Settlement Offer: ...,"['Workplace Hazards and Violations', 'Football...",News
11,5adf6684068401528a2aa69b,An easier solution for the women who do not no...,comment,approved,0,KB,"Brewster,NY",By JOHN BRANCH,781,Former N.F.L. Cheerleaders’ Settlement Offer: ...,"['Workplace Hazards and Violations', 'Football...",News
12,5adf6684068401528a2aa69b,Their job is to be literal sex objects. Instea...,comment,approved,0,Sarah Johnson,New York,By JOHN BRANCH,781,Former N.F.L. Cheerleaders’ Settlement Offer: ...,"['Workplace Hazards and Violations', 'Football...",News
13,5adf6684068401528a2aa69b,What an awful job: less than minimum wage; sho...,comment,approved,0,Benjamin Teral,"San Francisco, CA",By JOHN BRANCH,781,Former N.F.L. Cheerleaders’ Settlement Offer: ...,"['Workplace Hazards and Violations', 'Football...",News
14,5adf6684068401528a2aa69b,It would be easier for Goodell to give them $1...,comment,approved,0,Maturin25,South Carolina,By JOHN BRANCH,781,Former N.F.L. Cheerleaders’ Settlement Offer: ...,"['Workplace Hazards and Violations', 'Football...",News
15,5adf6684068401528a2aa69b,"NFL cheerleaders are underpaid, discriminated ...",comment,approved,0,Shamrock,Westfield,By JOHN BRANCH,781,Former N.F.L. Cheerleaders’ Settlement Offer: ...,"['Workplace Hazards and Violations', 'Football...",News
16,5adf6684068401528a2aa69b,These “cheerleaders” are apparently working fo...,comment,approved,0,Shamrock,Westfield,By JOHN BRANCH,781,Former N.F.L. Cheerleaders’ Settlement Offer: ...,"['Workplace Hazards and Violations', 'Football...",News
17,5adf6684068401528a2aa69b,"Most pro sports (baseball, basketball, footbal...",comment,approved,0,Jay David,NM,By JOHN BRANCH,781,Former N.F.L. Cheerleaders’ Settlement Offer: ...,"['Workplace Hazards and Violations', 'Football...",News
18,5adf6684068401528a2aa69b,Come on NYT. A serious article about a serious...,comment,approved,0,Dan Beekley,"Oregon, France",By JOHN BRANCH,781,Former N.F.L. Cheerleaders’ Settlement Offer: ...,"['Workplace Hazards and Violations', 'Football...",News
19,5adf6684068401528a2aa69b,What could possibly be more square and unhip t...,comment,approved,0,Richard Steele,"Santa Monica, CA",By JOHN BRANCH,781,Former N.F.L. Cheerleaders’ Settlement Offer: ...,"['Workplace Hazards and Violations', 'Football...",News
20,5adf6684068401528a2aa69b,The cover photo for this story tells it all: a...,comment,approved,0,Amy Haible,"Harpswell, Maine",By JOHN BRANCH,781,Former N.F.L. Cheerleaders’ Settlement Offer: ...,"['Workplace Hazards and Violations', 'Football...",News
21,5adf6684068401528a2aa69b,I'm of conflicting thoughts on the NFL cheerle...,comment,approved,0,HapinOregon,Southwest Corner of Oregon,By JOHN BRANCH,781,Former N.F.L. Cheerleaders’ Settlement Offer: ...,"['Workplace Hazards and Violations', 'Football...",News
22,5adf6684068401528a2aa69b,A savvy and excellent play by the women!,comment,approved,0,David Cohen,Oakland CA,By JOHN BRANCH,781,Former N.F.L. Cheerleaders’ Settlement Offer: ...,"['Workplace Hazards and Violations', 'Football...",News
23,5adf6684068401528a2aa69b,If the women cheerleaders/dancers find it deme...,comment,approved,0,James,Atlanta,By JOHN BRANCH,781,Former N.F.L. Cheerleaders’ Settlement Offer: ...,"['Workplace Hazards and Violations', 'Football...",News
24,5adf6684068401528a2aa69b,And there is no war on NFL football? A limitle...,comment,approved,0,Shamrock,Westfield,By JOHN BRANCH,781,Former N.F.L. Cheerleaders’ Settlement Offer: ...,"['Workplace Hazards and Violations', 'Football...",News
25,5adf6684068401528a2aa69b,"Just to be a little bit cynical, but this offe...",comment,approved,0,upstate now,saugerties ny,By JOHN BRANCH,781,Former N.F.L. Cheerleaders’ Settlement Offer: ...,"['Workplace Hazards and Violations', 'Football...",News
26,5adf6684068401528a2aa69b,Classy move. Good luck to them.,comment,approved,0,Tautala So'o,Samoa,By JOHN BRANCH,781,Former N.F.L. Cheerleaders’ Settlement Offer: ...,"['Workplace Hazards and Violations', 'Football...",News
27,5adf6684068401528a2aa69b,Women complain about being sexualized and yet ...,comment,approved,0,mrpisces,Louisiana,By JOHN BRANCH,781,Former N.F.L. Cheerleaders’ Settlement Offer: ...,"['Workplace Hazards and Violations', 'Football...",News
28,5adf6684068401528a2aa69b,"The ball is in your court, Mr. Goodell!",comment,approved,0,Rose in PA,Pennsylvania,By JOHN BRANCH,781,Former N.F.L. Cheerleaders’ Settlement Offer: ...,"['Workplace Hazards and Violations', 'Football...",News
29,5adf6684068401528a2aa69b,These women have a point to be made and not a ...,comment,approved,0,BTO,"Somerset, MA",By JOHN BRANCH,781,Former N.F.L. Cheerleaders’ Settlement Offer: ...,"['Workplace Hazards and Violations', 'Football...",News
...,...,...,...,...,...,...,...,...,...,...,...,...
257631,5ae82ca3068401528a2ab97a,"Was A Doll's House, Part II snubbed?<br/>I tho...",comment,approved,0,Stan Carlisle,Nightmare Alley,By MICHAEL PAULSON,2055,Unknown,"['Theater', 'Tony Awards (Theater Awards)', 'A...",News
257632,5ae82ca3068401528a2ab97a,Amy Schumer is the luckiest person in all of s...,comment,approved,0,Danielle,New York,By MICHAEL PAULSON,2055,Unknown,"['Theater', 'Tony Awards (Theater Awards)', 'A...",News
257633,5ae82ca3068401528a2ab97a,Sponge Bob and Mean Girls represent Broadway t...,comment,approved,0,Ken,Rancho Mirage,By MICHAEL PAULSON,2055,Unknown,"['Theater', 'Tony Awards (Theater Awards)', 'A...",News
257634,5ae82ca3068401528a2ab97a,Angels in America are TWO of the greatest play...,comment,approved,0,D,NYC,By MICHAEL PAULSON,2055,Unknown,"['Theater', 'Tony Awards (Theater Awards)', 'A...",News
257635,5ae82ca3068401528a2ab97a,The Great White Way has become Cartoon Alley. ...,comment,approved,0,Ed L,"Belgrade, ME",By MICHAEL PAULSON,2055,Unknown,"['Theater', 'Tony Awards (Theater Awards)', 'A...",News
257636,5ae82ca3068401528a2ab97a,I hope they choose a winner that will sell lot...,comment,approved,0,Eric,Minneapolis,By MICHAEL PAULSON,2055,Unknown,"['Theater', 'Tony Awards (Theater Awards)', 'A...",News
257637,5ae82ca3068401528a2ab97a,"Love Amy Schemer, but she's not yet a stage ac...",comment,approved,0,SNA,New Jersey,By MICHAEL PAULSON,2055,Unknown,"['Theater', 'Tony Awards (Theater Awards)', 'A...",News
257638,5ae82ca3068401528a2ab97a,Some Broadway. Some Tonys. Mediocre movies and...,comment,approved,0,marrtyy,manhattan,By MICHAEL PAULSON,2055,Unknown,"['Theater', 'Tony Awards (Theater Awards)', 'A...",News
257639,5ae82ca3068401528a2ab97a,I absolutely HATE Spongebob the cartoon on Nic...,comment,approved,0,A,California,By MICHAEL PAULSON,2055,Unknown,"['Theater', 'Tony Awards (Theater Awards)', 'A...",News
257640,5ae82ca3068401528a2ab97a,So how many decades has it been since there's ...,comment,approved,0,Tyrone,NYC,By MICHAEL PAULSON,2055,Unknown,"['Theater', 'Tony Awards (Theater Awards)', 'A...",News
257641,5ae82ca3068401528a2ab97a,"So GLENDA JACKSON is not ""boldface name""?",comment,approved,0,Ed L,"Belgrade, ME",By MICHAEL PAULSON,2055,Unknown,"['Theater', 'Tony Awards (Theater Awards)', 'A...",News
257642,5ae82ca3068401528a2ab97a,"Kiddie books, characters, cartoon idiocy. Poo...",comment,approved,0,Betsy Herring,"Edmond, OK",By MICHAEL PAULSON,2055,Unknown,"['Theater', 'Tony Awards (Theater Awards)', 'A...",News
257643,5ae82ca3068401528a2ab97a,"so, this is Broadway now?...SpongeBob, Frozen,...",comment,approved,0,Jim,NH,By MICHAEL PAULSON,2055,Unknown,"['Theater', 'Tony Awards (Theater Awards)', 'A...",News
257644,5ae82ca3068401528a2ab97a,I'm hoping the Band's Visit takes it away. If ...,comment,approved,0,llopez,NY,By MICHAEL PAULSON,2055,Unknown,"['Theater', 'Tony Awards (Theater Awards)', 'A...",News
257645,5ae82ca3068401528a2ab97a,The Schumer nomination is a desperate attempt ...,comment,approved,0,DSM14,Westfield NJ,By MICHAEL PAULSON,2055,Unknown,"['Theater', 'Tony Awards (Theater Awards)', 'A...",News
257646,5ae82ca3068401528a2ab97a,"In the system for receiving, recording, and co...",comment,approved,0,Dick Purcell,"Leadville, CO",By MICHAEL PAULSON,2055,Unknown,"['Theater', 'Tony Awards (Theater Awards)', 'A...",News
257647,5ae82ca3068401528a2ab97a,“Travesties” was on Broadway in the 70s. In f...,userReply,approved,0,NYCJP,NYC,By MICHAEL PAULSON,2055,Unknown,"['Theater', 'Tony Awards (Theater Awards)', 'A...",News
257648,5ae82ca3068401528a2ab97a,I heard a rumor they may add a number for Ms. ...,userReply,approved,0,Freddie,New York NY,By MICHAEL PAULSON,2055,Unknown,"['Theater', 'Tony Awards (Theater Awards)', 'A...",News
257649,5ae82ca3068401528a2ab97a,"Is than difficult lol, i'm just looking summar...",userReply,approved,0,@Aleydiwinski,"Veracruz, Mex",By MICHAEL PAULSON,2055,Unknown,"['Theater', 'Tony Awards (Theater Awards)', 'A...",News
257650,5ae82ca3068401528a2ab97a,I imagine the cast and/or theatre weren’t avai...,userReply,approved,0,NYCJP,NYC,By MICHAEL PAULSON,2055,Unknown,"['Theater', 'Tony Awards (Theater Awards)', 'A...",News
257651,5ae82ca3068401528a2ab97a,Doll's House Part II isn't eligible this year....,userReply,approved,0,Erin,New York,By MICHAEL PAULSON,2055,Unknown,"['Theater', 'Tony Awards (Theater Awards)', 'A...",News
257652,5ae82ca3068401528a2ab97a,"A Doll’s House, Part 2 by Lucas Heath was, ind...",userReply,approved,0,Mindi Reich-Shapiro,NYC,By MICHAEL PAULSON,2055,Unknown,"['Theater', 'Tony Awards (Theater Awards)', 'A...",News
257653,5ae82ca3068401528a2ab97a,Having talent is luck in and of itself also yo...,userReply,approved,0,Freddie,New York NY,By MICHAEL PAULSON,2055,Unknown,"['Theater', 'Tony Awards (Theater Awards)', 'A...",News
257654,5ae82ca3068401528a2ab97a,I feel exactly the same way. Spongebob doesn't...,userReply,approved,0,SJG,"NY, NY",By MICHAEL PAULSON,2055,Unknown,"['Theater', 'Tony Awards (Theater Awards)', 'A...",News
257655,5ae82ca3068401528a2ab97a,"This decade (Hamilton, Drowsy Chaperone, Last ...",userReply,approved,0,D,NYC,By MICHAEL PAULSON,2055,Unknown,"['Theater', 'Tony Awards (Theater Awards)', 'A...",News
257656,5ae82ca3068401528a2ab97a,This year was uniquely unoriginal - the four n...,userReply,approved,1,Michael Trenteseau,Atlanta,By MICHAEL PAULSON,2055,Unknown,"['Theater', 'Tony Awards (Theater Awards)', 'A...",News
257657,5ae82ca3068401528a2ab97a,"Come From Away, last year...",userReply,approved,0,Mia,Pittsburgh,By MICHAEL PAULSON,2055,Unknown,"['Theater', 'Tony Awards (Theater Awards)', 'A...",News
257658,5ae82ca3068401528a2ab97a,I love this quiet little musical. Exquisite pe...,userReply,approved,0,Mindi Reich-Shapiro,NYC,By MICHAEL PAULSON,2055,Unknown,"['Theater', 'Tony Awards (Theater Awards)', 'A...",News
257659,5ae82ca3068401528a2ab97a,We saw it about 10 days ago. Agree with your ...,userReply,approved,0,Bob G,St. Louis,By MICHAEL PAULSON,2055,Unknown,"['Theater', 'Tony Awards (Theater Awards)', 'A...",News
257660,5ae82ca3068401528a2ab97a,Spot on! I'm appalled by the Schumer nod!!!!!,userReply,approved,0,person of interest,seattle,By MICHAEL PAULSON,2055,Unknown,"['Theater', 'Tony Awards (Theater Awards)', 'A...",News

In [7]:
nyt_articles_df =merge_table.rename(index=str, columns={"commentBody": "Comment", "userDisplayName": "Username", "byline": "Author", 
                                       "articleID": "ArticleID",
                                       "commentType": "CommentType", "status": "Status", "trusted": "Trusted",
                                      "userLocation": "UserLocation", "articleWordCount": "ArticleWordCount",
                                      "headline": "Headline", "keywords": "Keywords", "typeOfMaterial":"TypeofMaterial"})

nyt_articles_df.head()

,ArticleID,Comment,CommentType,Status,Trusted,Username,UserLocation,Author,ArticleWordCount,Headline,Keywords,TypeofMaterial
0,5adf6684068401528a2aa69b,How could the league possibly refuse this offe...,comment,approved,0,Christopher Rillo,San Francisco,By JOHN BRANCH,781,Former N.F.L. Cheerleaders’ Settlement Offer: ...,"['Workplace Hazards and Violations', 'Football...",News
1,5adf6684068401528a2aa69b,"So then the execs can be like ""yeah...we will ...",comment,approved,0,Matt Brand,"Williamsburg, Brooklyn",By JOHN BRANCH,781,Former N.F.L. Cheerleaders’ Settlement Offer: ...,"['Workplace Hazards and Violations', 'Football...",News
2,5adf6684068401528a2aa69b,I would not want to play chess against these c...,comment,approved,0,Joseph,"Fayetteville, AR",By JOHN BRANCH,781,Former N.F.L. Cheerleaders’ Settlement Offer: ...,"['Workplace Hazards and Violations', 'Football...",News
3,5adf6684068401528a2aa69b,Could the cheerleaders join the Actors' Equity...,comment,approved,0,Stephen,"Phoenix, AZ",By JOHN BRANCH,781,Former N.F.L. Cheerleaders’ Settlement Offer: ...,"['Workplace Hazards and Violations', 'Football...",News
4,5adf6684068401528a2aa69b,We all know that if the cheerleaders were all ...,comment,approved,0,Greg,Seattle,By JOHN BRANCH,781,Former N.F.L. Cheerleaders’ Settlement Offer: ...,"['Workplace Hazards and Violations', 'Football...",News

In [8]:
connection_string = f"root:Muskies95!!@localhost/NYT_db"
engine = create_engine(f'mysql://{connection_string}')

In [9]:
engine.table_names()

['article_comments']

In [12]:
nyt_articles_df.to_sql(name="article_comments", con=engine, if_exists="append", index=True)

UnicodeEncodeError: 'latin-1' codec can't encode character '\u2019' in position 26: ordinal not in range(256)